config/routes.rb
Rails.application.routes.draw do
  resources :tasks
  resources :chores
  resources :bugs
  resources :features
  resources :tickets
  resources :states
  resources :epics
  resources :projects
  resources :teams
  resources :users

end

app/models/epic.rb
class Epic < ActiveRecord::Base
  belongs_to :project
  has_many :features
end

app/controllers/epics_controller.rb
class EpicsController < ApplicationController
  before_action :set_epic, only: [:show, :edit, :update, :destroy]

  # GET /epics
  # GET /epics.json
  def index
    @epics = Epic.all
  end

  # GET /epics/1
  # GET /epics/1.json
  def show
  end

  # GET /epics/new
  def new
    @epic = Epic.new
  end

  # GET /epics/1/edit
  def edit
  end

  # POST /epics
  # POST /epics.json
  def create
    @epic = Epic.new(epic_params)

    respond_to do |format|
      if @epic.save
        format.html { redirect_to @epic, notice: 'Epic was successfully created.' }
        format.json { render :show, status: :created, location: @epic }
      else
        format.html { render :new }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /epics/1
  # PATCH/PUT /epics/1.json
  def update
    respond_to do |format|
      if @epic.update(epic_params)
        format.html { redirect_to @epic, notice: 'Epic was successfully updated.' }
        format.json { render :show, status: :ok, location: @epic }
      else
        format.html { render :edit }
        format.json { render json: @epic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /epics/1
  # DELETE /epics/1.json
  def destroy
    @epic.destroy
    respond_to do |format|
      format.html { redirect_to epics_url, notice: 'Epic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_epic
      @epic = Epic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def epic_params
      params.require(:epic).permit(:name, :project_id)
    end
end

app/views/epics/_form.html.erb
<%= form_for(@epic) do |f| %>
  <% if @epic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@epic.errors.count, "error") %> prohibited this epic from being saved:</h2>

      <ul>
      <% @epic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.text_field :project_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/epics/edit.html.erb
<h1>Editing Epic</h1>

<%= render 'form' %>

<%= link_to 'Show', @epic %> |
<%= link_to 'Back', epics_path %>

app/views/epics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Epics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Project</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @epics.each do |epic| %>
      <tr>
        <td><%= epic.name %></td>
        <td><%= epic.project %></td>
        <td><%= link_to 'Show', epic %></td>
        <td><%= link_to 'Edit', edit_epic_path(epic) %></td>
        <td><%= link_to 'Destroy', epic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Epic', new_epic_path %>

app/views/epics/new.html.erb
<h1>New Epic</h1>

<%= render 'form' %>

<%= link_to 'Back', epics_path %>

app/views/epics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @epic.name %>
</p>

<p>
  <strong>Project:</strong>
  <%= @epic.project %>
</p>

<%= link_to 'Edit', edit_epic_path(@epic) %> |
<%= link_to 'Back', epics_path %>